# Generated by Django 5.1.1 on 2024-09-28 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaDulce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('nombre_receta', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_subida', models.DateField(default=django.utils.timezone.now)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
