# Generated by Django 5.1.1 on 2024-09-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_recetadulce'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('nombre_receta', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_subida', models.DateField()),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecetaSalada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('nombre_receta', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_subida', models.DateField()),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='recetadulce',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recetadulce',
            name='fecha_subida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recetadulce',
            name='nombre_receta',
            field=models.CharField(max_length=200),
        ),
    ]
